config/routes.rb
Rails.application.routes.draw do
  root "stories#index"
  resources :stories do
    resources :scenes do
      member do
        post :next
      end
      resources :paths
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/path.rb
class Path < ApplicationRecord
    belongs_to :scene, foreign_key: "scene_id"
end

app/models/scene.rb
class Scene < ApplicationRecord
    belongs_to :story, foreign_key: "story_id"
    has_many :paths, dependent: :destroy
end

app/models/story.rb
class Story < ApplicationRecord
    has_many :scenes, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/braille_cell_controller.rb
class BrailleCellController < ApplicationController
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy, :next]
  protect_from_forgery with: :null_session

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.build
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.build(scene_params)
    @scene.save
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def next
    @b1 = params[:b1]
    @b2 = params[:b2]
    @b3 = params[:b3]
    @b4 = params[:b4]
    @b5 = params[:b5]
    @b6 = params[:b6]
    @path = @scene.paths
    print(@path.empty?)
    @story = Story.find(params[:story_id])
    if @b1 == "on"
      redirect_to story_scene_path(@story, 1)
    elsif @b3 == "on"
      redirect_to story_scene_path(@story, 2)
    elsif @b5 == "on"
      redirect_to story_scene_path(@story, 3)
    else
      redirect_to story_path(@story)
    end
  end
  # def show_start_scene
  #   @story = Story.find(params[:story_id])
  #   @scena = @story.scenes.first
  #   redirect_to story_scene_path(@scena)
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_scene
    @scene = Scene.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scene_params
    params.require(:scene).permit(:texto)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @scene = @story.scenes.first
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.save
    redirect_to stories_path
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    @story.update(story_params)
    redirect_to stories_path
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    print(@story.titulo)
    @story.destroy
    redirect_to stories_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def story_params
    params.require(:story).permit(:titulo,:introducao)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braille_cell_helper.rb
module BrailleCellHelper
end

app/helpers/path_helper.rb
module PathHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/braille_cell/_form.html.erb
<form action="scenes/show">
  <div class="row center-align footer div-form-braillecell">
    <div class="col s6"><label><input type="checkbox" value ="b1" id="brailleCell1"/><span>B1</span></label></div>
    <div class="col s6"><label><input type="checkbox" value ="b2" id="brailleCell2"/><span>B2</span></label></div>
    <div class="col s6"><label><input type="checkbox" value ="b3" id="brailleCell3"/><span>B3</span></label></div>
    <div class="col s6"><label><input type="checkbox" value ="b4" id="brailleCell4"/><span>B4</span></label></div>
    <div class="col s6"><label><input type="checkbox" value ="b5" id="brailleCell5"/><span>B5</span></label></div>
    <div class="col s6"><label><input type="checkbox" value ="b6" id="brailleCell6"/><span>B6</span></label></div>
    <div class="col s12"><label><input type="submit" value ="Enter" class="btn enter-braille-cell"/></label></div>
  <div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>

  <body>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/scenes/_braille_cell.html.erb
<footer>
  <%=form_tag({:action => 'next'}, {:id => 'scene_id'}) do %>
    <div class="row center-align footer div-form-braillecell">
      <div class="col s6"><label><input type="checkbox" name = "b1" id="brailleCell1"/><span>B1</span></label></div>
      <div class="col s6"><label><input type="checkbox" name = "b2" id="brailleCell2"/><span>B2</span></label></div>
      <div class="col s6"><label><input type="checkbox" name = "b3" id="brailleCell3"/><span>B3</span></label></div>
      <div class="col s6"><label><input type="checkbox" name = "b4" id="brailleCell4"/><span>B4</span></label></div>
      <div class="col s6"><label><input type="checkbox" name = "b5" id="brailleCell5"/><span>B5</span></label></div>
      <div class="col s6"><label><input type="checkbox" name = "b6" id="brailleCell6"/><span>B6</span></label></div>
      <div class="col s12"><label><input type="submit" value ="Enter" class="btn enter-braille-cell"/></label></div>
    <div>
  <%end%>
</footer>

app/views/scenes/_form.html.erb
<%=form_for([@story,@scene]) do |form|%>
  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenes</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.texto %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_story_scene_path %>

app/views/scenes/new.html.erb
<h1>New Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Back', stories_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @scene.texto %>
</p>

<%=render "braille_cell"%>

app/views/scenes/start.html.erb
Ta certo

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
    <%= form.label :introducao %>
    <%= form.text_area :introducao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<header><h1 class="centralizado">Braille game</h1></header>
<div class="row">
  <div class="col s12 center-align"><h4>Histórias</h4></div>
    <% @stories.each do |story| %>
      <div class="col s4">
        <div class="card">
          <div class="card-content">
            <span class="card-title"><%=story.titulo%></span>
          </div>
          <div class="card-action">
            <%= link_to story do %>
              <%= content_tag :span, "Jogar", class:"waves-effect waves-light btn" %>
            <% end %>
            <%= link_to edit_story_path(story) do %>
              <%= content_tag :span, "Editar", class:"waves-effect waves-light btn" %>
            <% end %>
            <%= link_to story_path(story), method: :delete do %>
              <%= content_tag :span, "Deletar", class:"waves-effect waves-light btn" %>
            <% end %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>
<div class="row">
    <div class="col s12 center-align">
        <%= link_to new_story_path do %>
            <%= content_tag :span, "Nova história", class:"waves-effect waves-light btn botoes-inicias" %>
        <% end %>
    </div>
</div>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "row">
    <div class="col s12 box-texto">
        <p class="text" id="texto">
            <%=@story.introducao%>
            <%# <script> %>
                <%# typeWriter(<%=@story.introducao) %>
            <%# </script> %>
        </p>
    </div>
    <div class="col s12 center-align">
        <%if @story.scenes.empty?%>
            <%= link_to stories_path do %>
                <%= content_tag :span, "Voltar", class:"waves-effect waves-light btn botoes-inicias" %>
            <% end %>
        <%else%>
            <%= link_to story_scene_path(@story, @scene) do %>
                <%= content_tag :span, "Iniciar aventura", class:"waves-effect waves-light btn botoes-inicias" %>
            <% end %>
        <%end%>
    </div>
</div>